language: node_js
node_js:
  - '6.2'
  - '6.1'
  - '6.0'
  - '5.11'
  - '4.4'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-sf-redux' ]; then cd .. && eval "mv $currentfolder generator-sf-redux" && cd generator-sf-redux; fi
